### ISSUE TITLE
When I try to test ANE , app crashes

### ISSUE THREAD

**Issue by agoldust** [myflashlab/fileChooser-ANE#1]
Hi
When I try to test ANE , app crashes on my mobile with this message:
"Unfortunately, SERP-debug has stopped."

I described the details in below
please let me know where I am doing wrong?

thanks

------------------------
here is my code:
import com.doitflash.air.extensions.Dependency;
import com.doitflash.air.extensions.fileChooser.FileChooser;
import com.doitflash.air.extensions.fileChooser.FileChooserEvent;
import com.doitflash.tools.sizeControl.FileSizeConvertor;

  trace(Dependency.EXTENSION_ID + " = V" + Dependency.VERSION);

  var _ex:FileChooser = new FileChooser();
  _ex.addEventListener(FileChooserEvent.RESULT, onResult);
  _ex.addEventListener(FileChooserEvent.ERROR,  onError);
  _ex.choose("*/*", "pick a file!");

------------------------
and here is the result on Console:
com.doitflash.air.extensions.dependency = V1.0

and when app wanted to call _ex.choose(), the "_ex.context.actionScriptData" is null 

------------------------------------------
my mobile is using android 4.0.3

I am using:
- Adobe Flash Builder 4.6
- Apache Flex SDK 4.14.1 with Adobe AIR 17

I added this 2 ane to my ane folder and added via "Flash Build Path"  > "Native Extentions".
- commonDependencies.ane
- fileBrowserExtension.ane

and added this infos into my Manifest file:'

     <application android:hardwareAccelerated="true" android:allowBackup="true">
	<activity android:hardwareAccelerated="false">
		<intent-filter>
			<action android:name="android.intent.action.MAIN" />
			<category android:name="android.intent.category.LAUNCHER" />
		</intent-filter>
	</activity>

	<activity android:name="com.doitflash.fileBrowser.Chooser" android:theme="@style/Theme.Transparent" />
     </application>

	<extensions>
            <extensionID>com.doitflash.air.extensions.fileBrowser</extensionID>
            <extensionID>com.doitflash.air.extensions.dependency</extensionID>
	</extensions>

**Comment by myflashlab** [comment]
does it also crash when running the demo .apk?
are you missing the file type? _ex.choose("*/*", "pick a file!");

**Comment by agoldust** [comment]
I wrote that mimetype correct but github is not showing it

also I found the problem
I was using Adobe AIR 17 and app was not working, don't know why
today I changed that to AIR 18 Beta, it worked

Thanks for this great Extension :)

**Comment by myflashlab** [comment]
And by the way, you don't have to import com.doitflash.air.extensions.Dependency; into your project at all. just adding it to the manifest is enough.
