### ISSUE TITLE
How to choose non-image files, like PDF, MS Office (doc, xls, ppt)

### ISSUE THREAD

**Issue by chetan1997** [myflashlab/fileChooser-ANE#10]
I am using Version-26 of myflashlabs pack.

I need the ANE to choose files other than images, like PDF, .doc/x, .xls/x and .ppt/x.  MS Office docs (for example .xls and .xlsx) can be selected in FileChooser using two different mime types (application/vnd.ms-excel for .xls and application/vnd.openxmlformats-officedocument.spreadsheetml.sheet for .xlsx).  FileChooser lists such files correctly when called with either one of these mimes.

But I want to the user to select ANY spreadsheet.  What should I pass as mime to choose() to select any spreadsheet (.xls or .xlsx) ?

Thanks.

**Comment by myflashlab** [comment]
The first thing to add is that you can choose different file types on Android only because iOS does not allow it. Besides that, you can set the mimetype using the first parameter of the ```choose``` method.

```actionscript
// means any file
_ex.choose("*/*", "pick a file!"); 

// means any image file, no matter the extension, png, jpg, etc
_ex.choose("image/*", "pick an image!"
```

For spreadsheet files, we really don't have much experience with them but you should be able to find a correct mimetype for them on probably asking on Stackoverflow...

**Comment by chetan1997** [comment]
I've quoted the mimetype for xls and xlsx types in my original post.  They both work with FileChooser when invoked with one mimetype at a time.   (_Mimetypes: application/vnd.ms-excel for .xls and application/vnd.openxmlformats-officedocument.spreadsheetml.sheet for .xlsx_).

The user of the App doesn't distinguish between xls and xlsx - they just want to select a Spreadsheet file.  So, my question is how can I ask FileChooser to select ANY spreadsheet file?  Passing both mimeytypes with several different separator characters doesn't work.

Is it at all possible to pass more that one mimetype to FileChooser in one choose() call?

**Comment by myflashlab** [comment]
aha, file types are actually different. Ok, unfortunately nope. We are not currently supporting multiple mimetypes but I am marking this issue so we can consider adding the feature to the ANE in future.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
