### ISSUE TITLE
Not close pick file screen after choose a file.

### ISSUE THREAD

**Issue by giabao** [myflashlab/fileChooser-ANE#11]
When i picked a image on Android, i have received FileChooserEvent.RESULT event but  pick file screen is still visible.

**Comment by myflashlab** [comment]
will you be able to send us a sample apk file so we can run it locally also and see the problem?

**Comment by myflashlab** [comment]
This issue has been inactive for a long time so I m closing it now, but if you have more info about this issue, let us know and I'll re-open it to debug the problem.
