### ISSUE TITLE
Issue #10, about mimetype for FileChooser.choose() closed without answer - so creating new issue.

### ISSUE THREAD

**Issue by chetan1997** [myflashlab/fileChooser-ANE#12]
Issue number 10 was closed without much of an answer.  So I am posting this issue again so that we can find a closure to this question:

I've quoted the mimetype for xls and xlsx types in my original post. They both work with FileChooser when invoked with one mimetype at a time. (Mimetypes: application/vnd.ms-excel for .xls and application/vnd.openxmlformats-officedocument.spreadsheetml.sheet for .xlsx).

The user of the App doesn't distinguish between xls and xlsx - they just want to select a Spreadsheet file. So, my question is how can I ask FileChooser to select ANY spreadsheet file? Passing both mimeytypes with several different separator characters doesn't work.

Is it at all possible to pass more that one mimetype to FileChooser in one choose() call?

**Comment by myflashlab** [comment]
please continue on https://github.com/myflashlab/fileChooser-ANE/issues/10 I just reopened that issue.
