### ISSUE TITLE
Start image picking from a specific directory

### ISSUE THREAD

**Issue by syberkitten** [myflashlab/fileChooser-ANE#13]
Is it possible to start the fileChooser from a specific folder?

My app saves user images inside File.DocumentsDirectory(), thus: Pictures/myapp/images
how can i start the ANE picking files from this folder?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
