### ISSUE TITLE
Starling / Feathers compatible? 

### ISSUE THREAD

**Issue by barksdontduck** [myflashlab/fileChooser-ANE#14]
I purchased this ANE and the permissions one. I'm wondering if this can play well with Starling / Feathers? So far, I haven't had any luck. Nothing happens when I call the FileChooser choose(...) function.

**Comment by myflashlab** [comment]
it should work fine on Starling projects too. You mean you have been able to open the dialog on non-starling project but it didn't work on a starling one?

**Comment by kakarlus** [comment]
@barksdontduck i just bought this one too, im using it with Starling & Feathers, it works as expected. share more info about what's not working so people can help you.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
