### ISSUE TITLE
App crashing after selecting image with file chooser

### ISSUE THREAD

**Issue by ThomasNeuro** [myflashlab/fileChooser-ANE#17]
Hi there, 
we are using the file chooser for letting the user choose profile pictures. In some cases our app is crashing with the following errors:

 Exception java.lang.RuntimeException: Unable to resume activity {air.nn.mobile.app.main/com.doitflash.fileBrowser.Chooser}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=6384, result=-1, data=Intent { dat=content://media/external/images/media/676 flg=0x1 }} to activity {air.nn.mobile.app.main/com.doitflash.fileBrowser.Chooser}: java.lang.NullPointerException
android.app.ActivityThread.performResumeActivity (ActivityThread.java:2919)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:2948)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2354)
android.app.ActivityThread.access$700 (ActivityThread.java:159)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1316)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:176)
android.app.ActivityThread.main (ActivityThread.java:5419)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:525)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1046)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:862)
dalvik.system.NativeStart.main (NativeStart.java)

Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=6384, result=-1, data=Intent { dat=content://media/external/images/media/676 flg=0x1 }} to activity {air.nn.mobile.app.main/com.doitflash.fileBrowser.Chooser}: java.lang.NullPointerException
android.app.ActivityThread.deliverResults (ActivityThread.java:3500)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:2906)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:2948)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2354)
android.app.ActivityThread.access$700 (ActivityThread.java:159)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1316)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:176)
android.app.ActivityThread.main (ActivityThread.java:5419)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:525)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1046)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:862)
dalvik.system.NativeStart.main (NativeStart.java)

 Caused by java.lang.NullPointerException:
android.widget.Toast.<init> (Toast.java:105)
android.widget.Toast.makeText (Toast.java:261)
com.doitflash.fileBrowser.AirCommand.toDispatchFileChooserError (AirCommand.java:137)
com.doitflash.fileBrowser.Chooser.onActivityResult (Chooser.java:93)
android.app.Activity.dispatchActivityResult (Activity.java:5563)
android.app.ActivityThread.deliverResults (ActivityThread.java:3496)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:2906)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:2948)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2354)
android.app.ActivityThread.access$700 (ActivityThread.java:159)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1316)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:176)
android.app.ActivityThread.main (ActivityThread.java:5419)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:525)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1046)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:862)
dalvik.system.NativeStart.main (NativeStart.java)

example specs form the crashing device are:
 Hersteller: Samsung
Modell: GT-I9300
Platine: Smdk4x12
Android API: 18
Android-Betriebssystem: 4.3
Marke: Samsung
RAM: 830.93MB
Ausrichtung: Hochformat 
 Freier VM-Speicherplatz: 1.35MB
VM-Speicherplatz insgesamt: 42.13MB
Maximaler VM-Speicherplatz: 64MB 

We are running with the latest Air 25 Sdk

Do you experienced similar issues?

Thanks in advance

**Comment by myflashlab** [comment]
It seems like while you are picking the image on the Android Activity, your AIR app closes! try to stop heavy processes on your AIR app and lower the framerate so when the focus is not on your AIR content, the OS is not closing it down.

**Comment by ThomasNeuro** [comment]
Thanks for reply, we need to see if we can do something. We are stopping starling but maybe worth a try to slow down the application itself.

**Comment by tfnsyl** [comment]
Hi, Same error here. Just like @ThomasNeuro, we are also stopping starling but this error occurs repeatedly. Anyone has a workaround?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
