### ISSUE TITLE
No video on ios

### ISSUE THREAD

**Issue by drmms86** [myflashlab/fileChooser-ANE#19]
I purchased this ANE only to be able to select video on iOS but i realized after that it can not be used for video on iOS. I think it is a waste of money as I can use CameraRoll to pick an image or another open source native extension.
Please fix that.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
