### ISSUE TITLE
How to configure flex manifast xml?

### ISSUE THREAD

**Issue by wangemilyj** [myflashlab/fileChooser-ANE#2]
I use this ane in a Flex project, how I can configure the mainifast file?
I add some code:
<application android:hardwareAccelerated="true" android:allowBackup="true">
				<activity android:hardwareAccelerated="false">
				    <intent-filter>
				        <action android:name="android.intent.action.MAIN" />
				        <category android:name="android.intent.category.LAUNCHER" />
				    </intent-filter>
				</activity>
			
				<activity android:name="com.doitflash.fileBrowser.Chooser" android:theme="@style/Theme.Transparent" />
			</application>
			<extensions>
		        <extensionID>com.doitflash.air.extensions.fileBrowser</extensionID>
			</extensions>

but it not work, it can not popup fileBrowser, can you help me on this?

**Comment by wangemilyj** [comment]
<application android:hardwareAccelerated="true" android:allowBackup="true">
				<activity android:hardwareAccelerated="false">
				    <intent-filter>
				        <action android:name="android.intent.action.MAIN" />
				        <category android:name="android.intent.category.LAUNCHER" />
				    </intent-filter>
				</activity>
			
				<activity android:name="com.doitflash.fileBrowser.Chooser" android:theme="@style/Theme.Transparent" />
			</application>
			<extensions>
		        <extensionID>com.doitflash.air.extensions.fileBrowser</extensionID>
			</extensions>

**Comment by myflashlab** [comment]
Your manifest seems fine. What error message are you receiving?

On Monday, July 27, 2015, wangemilyj <notifications@github.com> wrote:

> I use this ane in a Flex project, how I can configure the mainifast file?
> I add some code:
>
>
>
>
>
>
>              <activity android:name="com.doitflash.fileBrowser.Chooser" android:theme="@style/Theme.Transparent" />
>         </application>
>         <extensions>
>             <extensionID>com.doitflash.air.extensions.fileBrowser</extensionID>
>         </extensions>
>
> but it not work, it can not popup fileBrowser, can you help me on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/fileChooser-ANE/issues/2>.
>


-- 
Sent from iPhone

**Comment by wangemilyj** [comment]
Not any error message receiving, I set a button and regist listener in the application:
private function popupChooseUploadImgSelection():void{
				if(_ex == null){
					_ex = new FileChooser();
				}
				_ex.addEventListener(FileChooserEvent.RESULT, onResult);
				_ex.addEventListener(FileChooserEvent.ERROR, onError);
				_ex.choose("*/*", "pick a file!");
			}

private function onResult(e:FileChooserEvent):void{
				var file:File = e.param as File;
				if(file){
					
				}
			}

private function onError(e:FileChooserEvent):void
			{
				trace("onError = " + e.param);
			}

but the process not into onResult or onError function, looks like do any thing.
I using the newest air sdk:
<application xmlns="http://ns.adobe.com/air/application/18.0">

Do you have some advice for me?

**Comment by wangemilyj** [comment]
<application android:hardwareAccelerated="true" android:allowBackup="true">
				<activity android:hardwareAccelerated="false">
				    <intent-filter>
				        <action android:name="android.intent.action.MAIN" />
				        <category android:name="android.intent.category.LAUNCHER" />
				    </intent-filter>
				</activity>
				
				<activity android:name="com.doitflash.fileBrowser.Chooser" android:theme="@style/Theme.Transparent" />
				</application>
 
			
			</manifest>
			
			 
		]]></manifestAdditions>
		
		
			
</android>
    <iPhone>
        <InfoAdditions><![CDATA[
			<key>UIDeviceFamily</key>
			<array>
				<string>1</string>
				<string>2</string>
			</array>
		]]></InfoAdditions>
        <requestedDisplayResolution>high</requestedDisplayResolution>
    </iPhone>

<extensions>
        <extensionID>com.doitflash.air.extensions.fileBrowser</extensionID>
    
    <extensionID>com.doitflash.air.extensions.dependency</extensionID>
    </extensions>
</application>


it works!

**Comment by myflashlab** [comment]
good :)
