### ISSUE TITLE
App crash calling choose method if Facebook.init is called before

### ISSUE THREAD

**Issue by msmpro** [myflashlab/fileChooser-ANE#22]
## Environment ##
* Android API Version: 27
* iOS Version: 9
* AIR SDK Version: 29.0.0.122
* Tested on Android 6 and Android 8
* Tested with androidSupport-V27.0.2-full and androidSupport-V26.0.2-full

## Problem Description ##
The problem is only on ANDROID devices.
If I initialize Facebook ANE (Facebook.init) before calling "choose" method from File Chooser ANE, the app crash without showing any message.
To make choose file working again, it's necessary to restart the app and not fire any action who need to initialize Facebook ANE.

* Copy your manifest ```.xml``` file.
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<application xmlns="http://ns.adobe.com/air/application/29.0">

	<id>com.jjjj</id>

	<filename>jjjj</filename>

	<name>jjjjj</name>

	<copyright>Copyright (c) 2018</copyright>

	<versionNumber>1.1.0</versionNumber>

	<initialWindow>
		<content>[This value will be overwritten by Flash Builder in the output app.xml]</content>
		<renderMode>direct</renderMode>
		<depthAndStencil>true</depthAndStencil>
		<autoOrients>false</autoOrients>
		<fullScreen>false</fullScreen>
		<visible>true</visible>
		<softKeyboardBehavior>none</softKeyboardBehavior>
	</initialWindow>

	<icon>
		<image16x16>appIcon/Icon_16.png</image16x16>
		<image29x29>appIcon/Icon-Small.png</image29x29>
		<image32x32>appIcon/Icon_32.png</image32x32>
		<image36x36>appIcon/Icon_36.png</image36x36>
		<image40x40>appIcon/Icon-Notification@2x.png</image40x40>
		<image44x44>appIcon/Icon_44.png</image44x44>
		<image48x48>appIcon/Icon_48.png</image48x48>
		<image50x50>appIcon/Icon_50.png</image50x50>
		<image57x57>appIcon/Icon.png</image57x57>
		<image58x58>appIcon/Icon-Small@2x.png</image58x58>
		<image60x60>appIcon/Icon-Notification@3x.png</image60x60>
		<image66x66>appIcon/Icon_66.png</image66x66>
		<image72x72>appIcon/Icon-72.png</image72x72>
		<image75x75>appIcon/Icon_75.png</image75x75>
		<image76x76>appIcon/Icon-76.png</image76x76>
		<image80x80>appIcon/Icon-Small-80.png</image80x80>
		<image87x87>appIcon/Icon-Small@3x.png</image87x87>
		<image96x96>appIcon/Icon_96.png</image96x96>
		<image100x100>appIcon/Icon_100.png</image100x100>
		<image114x114>appIcon/Icon@2x.png</image114x114>
		<image120x120>appIcon/Icon-120.png</image120x120>
		<image128x128>appIcon/Icon_128.png</image128x128>
		<image144x144>appIcon/Icon-144.png</image144x144>
		<image152x152>appIcon/Icon-152.png</image152x152>
		<image167x167>appIcon/Icon-167.png</image167x167>
		<image180x180>appIcon/Icon-180.png</image180x180>
		<image192x192>appIcon/Icon_192.png</image192x192>
		<image512x512>appIcon/Icon_512.png</image512x512>
		<image1024x1024>appIcon/Icon-Store.png</image1024x1024>
	</icon>

	<android>
		<colorDepth>16bit</colorDepth>
		<manifestAdditions>
			<![CDATA[
			<manifest android:installLocation="auto">
			    <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="27"/>
			    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
			    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
			    <uses-permission android:name="android.permission.INTERNET"/>
			    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
 			    <uses-permission android:name="android.permission.VIBRATE"/>
			    <uses-permission android:name="android.permission.GET_TASKS"/>
 				<uses-permission android:name="android.permission.WAKE_LOCK"/>
 			    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  			    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
				<permission android:name="air.com.Myyapp.permission.C2D_MESSAGE" android:protectionLevel="signature" />
				<uses-permission android:name="air.com.Myyapp.permission.C2D_MESSAGE" />
				<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
				<application android:hardwareAccelerated="true" android:allowBackup="true">
					<receiver android:name="com.milkmangames.extensions.android.push.GCMBroadcastReceiver"
					android:permission="com.google.android.c2dm.permission.SEND" >
					<intent-filter>
						<action android:name="com.google.android.c2dm.intent.RECEIVE" />
						<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
						<category android:name="air.com.rMyyapp" />
					</intent-filter>
					</receiver>
					<service android:name="com.milkmangames.extensions.android.push.GCMIntentService" />
					
					<!-- File Chooser -->
					<activity android:name="com.doitflash.fileBrowser.Chooser" android:theme="@style/Theme.Transparent" />
					
					<!-- FB -->
					<activity android:hardwareAccelerated="false">
					    <intent-filter>
					        <action android:name="android.intent.action.MAIN" />
					        <category android:name="android.intent.category.LAUNCHER" />
					    </intent-filter>
					    <intent-filter>
					        <action android:name="android.intent.action.VIEW" />
					        <category android:name="android.intent.category.BROWSABLE" />
					        <category android:name="android.intent.category.DEFAULT" />
		                    <!-- Your application scheme. read here for more information: http://www.myflashlabs.com/open-adobe-air-app-browser-pass-parameters/ -->
		                    <data android:scheme="air.com.xxxxx" />
		                </intent-filter>
		            </activity>
					
					<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ XXXXXXXXXXXXXX"/>
					<activity
					    android:name="com.facebook.FacebookActivity"
					    android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
					    android:theme="@android:style/Theme.Translucent.NoTitleBar"
					    android:label="Myyapp" />
					    
					<activity android:name="com.facebook.CustomTabMainActivity" />
					<activity android:name="com.facebook.CustomTabActivity" android:exported="true">
					    <intent-filter>
					        <action android:name="android.intent.action.VIEW" />
					        <category android:name="android.intent.category.DEFAULT" />
					        <category android:name="android.intent.category.BROWSABLE" />
					
					        <!-- Your facebook App ID here. keep the 'fb' prefix -->
					        <data android:scheme="fbXXXXXXX" />
					    </intent-filter>
					</activity>
					
					<provider
					    android:authorities="com.facebook.app.FacebookContentProviderXXXXXXX"
					    android:name="com.facebook.FacebookContentProvider"
					    android:exported="true" />
					
				</application>
			</manifest>
			
		]]>
		</manifestAdditions>
	</android>

	<iPhone>
		<Entitlements>
			<![CDATA[
				<key>application-identifier</key>
					<string>75775857.com.Myyapp</string>
				<key>aps-environment</key>
 					<string>production</string>		
				<key>keychain-access-groups</key>
				<array>
					<string>75775857.com.Myyapp</string>
				</array>
			]]>
		</Entitlements>
		<InfoAdditions>
			<![CDATA[
			<key>MinimumOSVersion</key>
	        <string>9.0</string>
	        
	        <key>UIStatusBarStyle</key>
			<string>UIStatusBarStyleBlackOpaque</string>

			<key>UIRequiresPersistentWiFi</key>
			<string>NO</string>
			
			<!-- Required by the statusbar.ane -->
			<key>UIViewControllerBasedStatusBarAppearance</key>
			<false/>
        
			<key>FacebookAppID</key>
			<string>75775857</string>
			
			<key>FacebookDisplayName</key>
			<string>Myyapp</string>
			
			<key>CFBundleURLTypes</key>
			<array>
				<dict>
					<key>CFBundleURLSchemes</key>
					<array>
						<string>fb75775857</string>
						<string>air.com.Myyapp</string>
					</array>
				</dict>
			</array>
			
			<!-- To whitelist Facebook Apps -->
	        <key>LSApplicationQueriesSchemes</key>
			<array>
			    <string>fbapi</string>
			    <string>fb-messenger-api</string>
			    <string>fb-messenger-share-api</string>
			    <string>fb-messenger</string>
			    <string>fbauth2</string>
			    <string>fbshareextension</string>
			</array>
			
			<key>UIDeviceFamily</key>
			<array>
				<string>1</string>
				<string>2</string>
			</array>
			
			<key>NSAppTransportSecurity</key>
			<dict>
				<key>NSExceptionDomains</key>
				<dict>
					<key>Myyapp.com</key>
						<dict>
							<!--Include to allow subdomains-->
							<key>NSIncludesSubdomains</key>
							<true/>
							<!--Include to allow HTTP requests-->
							<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
							<true/>
							<!--Include to specify minimum TLS version-->
							<key>NSTemporaryExceptionMinimumTLSVersion</key>
							<string>TLSv1.1</string>
						</dict>
				</dict>
			</dict>
			
			<key>NSCameraUsageDescription</key>
			<string>Access needed to add file to Gallery</string>
			<key>NSPhotoLibraryUsageDescription</key>
			<string>Access needed to add file to Gallery</string>
			
		]]>
		</InfoAdditions>
		<requestedDisplayResolution>high</requestedDisplayResolution>
	</iPhone>
	<extensions>
		<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
		<extensionID>com.myflashlab.air.extensions.facebook</extensionID>
		<extensionID>com.milkmangames.extensions.EasyPush</extensionID>


		<extensionID>com.myflashlab.air.extensions.statusbar</extensionID>
		<extensionID>com.myflashlab.air.extensions.fileBrowser</extensionID>
	</extensions>
</application>
```
## Steps to Reproduce ##
Initialize Facebook ANE (Facebook.init)
Initializar File Choosed ANE (fChooser = new FileChooser())
Call choose function from File Chooser ANE (fChooser.choose(......))

## Known Workarounds ##
Possible workaround/fix: Maybe a function to "dispose" the Facebook ANE?

**Comment by myflashlab** [comment]
Please copy the crash log from AndroidStudio logcats.

**Comment by msmpro** [comment]
Hi!
I'm using Flash Builder to launch the app on debug mode, and nothing is shown on log console.

**Comment by myflashlab** [comment]
Install AndroidStudio. create an empty dummy Android project just so you can open the logcat window. There, run your project while your device is connected and then watch the AndroidStudio logs. When the crash happens you should be able to see the logs. copy that part and send to us. Thanks.

FYI: AndroidStudio logcat for Android and xcode log console for iOS is the standard way to check native logs.

**Comment by msmpro** [comment]
@myflashlab thanks for the information about how to check native logs.
This is the log I get on Logcat:

`04-30 18:20:44.985 13502-13502/? I/Timeline: Timeline: Activity_launch_request id:air.com.myapp.runkeyapp time:1354821
04-30 18:20:44.985 869-2320/? D/CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 869  pkgName : ACTIVITY_RESUME_BOOSTER@10
04-30 18:20:44.985 869-2320/? D/ActivityManager: mDVFSHelper.acquire()
04-30 18:20:44.995 869-2320/? D/InputDispatcher: Focused application set to: xxxx
    Focus left window: 13502
04-30 18:20:44.995 869-1041/? D/PointerIcon: setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:869 uid:1000
    setMouseCustomIcon IconType is same.101
    setHoveringSpenIconStyle1 pointerType: 10001 iconType:1 flag:0 pid:869 uid:1000
    setHoveringSpenCustomIcon IconType is same.1
04-30 18:20:45.035 13502-13502/? D/[PushNotifyEx]: Pause.
04-30 18:20:45.045 13502-13502/? D/SensorManager: unregisterListener ::   
04-30 18:20:45.045 869-1328/? D/NetworkPolicy: isUidForegroundLocked: 10069, mScreenOn: true, uidstate: 7, mProxSensorScreenOff: false
04-30 18:20:45.055 13502-13502/? W/ResourcesManager: getTopLevelResources: /data/app/air.com.myapp.runkeyapp-1/base.apk / 1.0 running in air.com.myapp.runkeyapp rsrc of package null
04-30 18:20:45.055 13502-13502/? D/AndroidRuntime: Shutting down VM
04-30 18:20:45.065 13502-13502/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: air.com.myapp.runkeyapp, PID: 13502
    java.lang.NoClassDefFoundError: Failed resolution of: Lbolts/AppLinks;
        at com.facebook.appevents.internal.SourceApplicationInfo$Factory.create(SourceApplicationInfo.java:131)
        at com.facebook.appevents.internal.ActivityLifecycleTracker.onActivityCreated(ActivityLifecycleTracker.java:131)
        at com.facebook.appevents.internal.ActivityLifecycleTracker$1.onActivityCreated(ActivityLifecycleTracker.java:77)
        at android.app.Application.dispatchActivityCreated(Application.java:219)
        at android.app.Activity.onCreate(Activity.java:1039)
        at com.doitflash.fileBrowser.Chooser.onCreate(Chooser.java:35)
        at android.app.Activity.performCreate(Activity.java:6876)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.access$1100(ActivityThread.java:221)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "bolts.AppLinks" on path: DexPathList[[zip file "/data/app/air.com.myapp.runkeyapp-1/base.apk"],nativeLibraryDirectories=[/data/app/air.com.myapp.runkeyapp-1/lib/arm, /data/app/air.com.myapp.runkeyapp-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.facebook.appevents.internal.SourceApplicationInfo$Factory.create(SourceApplicationInfo.java:131) 
        at com.facebook.appevents.internal.ActivityLifecycleTracker.onActivityCreated(ActivityLifecycleTracker.java:131) 
        at com.facebook.appevents.internal.ActivityLifecycleTracker$1.onActivityCreated(ActivityLifecycleTracker.java:77) 
        at android.app.Application.dispatchActivityCreated(Application.java:219) 
        at android.app.Activity.onCreate(Activity.java:1039) 
        at com.doitflash.fileBrowser.Chooser.onCreate(Chooser.java:35) 
        at android.app.Activity.performCreate(Activity.java:6876) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7224) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
    	Suppressed: java.lang.ClassNotFoundException: bolts.AppLinks
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 19 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
04-30 18:20:45.095 1391-1391/? D/StatusBar.NetworkController: refreshViews connected={ wifi } level=4 combinedSignalIconId=0x7f020646/com.android.systemui:drawable/stat_sys_wifi_signal_3 mobileLabel=Sólo llamadas de emergencia wifiLabel="msm_wl_2_5G" emergencyOnly=true combinedLabel="msm_wl_2_5G" mAirplaneMode=false mDataActivity=0 mPhoneSignalIconId=0x7f0205c9/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mQSPhoneSignalIconId=0x7f02015e/com.android.systemui:drawable/ic_qs_signal_4 mDataDirectionIconId=0x0/(null) mDataSignalIconId=0x7f0205c9/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mDataTypeIconId=0x0/(null) mQSDataTypeIconId=0x0/(null) mNoSimIconId=0x0/(null) mWifiIconId=0x7f020646/com.android.systemui:drawable/stat_sys_wifi_signal_3 mQSWifiIconId=0x7f02032a/com.android.systemui:drawable/qs_tile_wifi_signal_3 mWifiActivityIconId=0x7f0205ff/com.android.systemui:drawable/stat_sys_signal_no_inout mBluetoothTetherIconId=0x7f020625/com.android.systemui:drawable/stat_sys_tether_bluetooth
    refreshNwBoosterIndicator - setNWBoosterIndicators(false)
04-30 18:20:45.115 1391-1391/? D/StatusBar.NetworkController: refreshNwBoosterIndicator - setNWBoosterIndicators(false)
    refreshNwBoosterIndicator - setNWBoosterIndicators(false)
    refreshNwBoosterIndicator - setNWBoosterIndicators(false)
04-30 18:20:45.145 869-2346/? W/ActivityManager:   Force finishing activity air.com.myapp.runkeyapp/com.doitflash.fileBrowser.Chooser
04-30 18:20:45.145 869-2346/? D/InputDispatcher: Focused application set to: xxxx
    Focus entered window: 13502
04-30 18:20:45.145 6864-6864/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1305 android.content.ContextWrapper.startService:606 android.content.ContextWrapper.startService:606 com.samsung.android.sm.common.SmartManagerReceiver.b:259 com.samsung.android.sm.common.SmartManagerReceiver.onReceive:107 
04-30 18:20:45.145 869-1041/? D/PointerIcon: setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:869 uid:1000
    setMouseCustomIcon IconType is same.101
    setHoveringSpenIconStyle1 pointerType: 10001 iconType:1 flag:0 pid:869 uid:1000
    setHoveringSpenCustomIcon IconType is same.1
04-30 18:20:45.145 869-2346/? W/ActivityManager:   Force finishing activity air.com.myapp.runkeyapp/.AppEntry
04-30 18:20:45.145 869-2346/? D/InputDispatcher: Focused application set to: xxxx
04-30 18:20:45.145 869-2346/? D/FocusedStackFrame: Set to : 0
04-30 18:20:45.145 869-2346/? D/InputDispatcher: Focus left window: 13502
04-30 18:20:45.155 869-1041/? D/PointerIcon: setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:869 uid:1000
    setMouseCustomIcon IconType is same.101
    setHoveringSpenIconStyle1 pointerType: 10001 iconType:1 flag:0 pid:869 uid:1000
    setHoveringSpenCustomIcon IconType is same.1
04-30 18:20:45.185 869-13884/? E/android.os.Debug: ro.product_ship = true
    ro.debug_level = 0x4f4c
    sys.mobilecare.preload = false
04-30 18:20:45.215 869-961/? D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{fd326e7 V.E...... R.....I. 0,0-0,0}
04-30 18:20:45.215 869-961/? D/ISSUE_DEBUG: InputChannelName : 30c013d Application Error: air.com.myapp.runkeyapp
04-30 18:20:45.215 869-961/? D/InputDispatcher: Focus entered window: 869`

**Comment by msmpro** [comment]
Hi!
I tested with the last version of ANE V4.30.1 and it's working fine!

Thank you for your support!
