### ISSUE TITLE
Unable to choose file on GoogleDrive

### ISSUE THREAD

**Issue by subdan** [myflashlab/fileChooser-ANE#24]
## Environment ##
* Android API Version: Android 5.1
* AIR SDK Version: 30.0.0

## Problem Description ##
I use the ANE to select a file on a device. When I call _ex.choose() new windows opens. In this window I see GoogleDrive button on the left sidebar. I press this button and choose file. App throws error:
[Fault] exception, information=ArgumentError: Error #2004: One of the parameters is invalid.
**Does the ANE supports selecting files on GoogleDrive? If no, how to hide GoogleDrive button on the left sidebar?**

## Steps to Reproduce ##
Try to select file on GoogleDrive. You will get:
[Fault] exception, information=ArgumentError: Error #2004: One of the parameters is invalid.

## Known Workarounds ##
No.

**Comment by myflashlab** [comment]
this feature is now added and you'll have access to it when V4.1.5 is released in a few days.
