### ISSUE TITLE
Cannot access a property or method of a null object reference.

### ISSUE THREAD

**Issue by njakatsifoiko** [myflashlab/fileChooser-ANE#26]
## Environment ##
* Android API Version: 
* iOS Version: 11
* AIR SDK Version: 30

## Problem Description ##
Hello, when I try to instanticiate  new FileChooser(), i got this error : Cannot access a property or method of a null object reference.

## code ##
import com.myflashlab.air.extensions.fileChooser.FileChooser;
var _ex:FileChooser = new FileChooser();

Thank you.

**Comment by xxxVBxxx** [comment]
Have you found the solution,?  I got the same error.

**Comment by njakatsifoiko** [comment]
Hi, no. When I wrote this issue, i had just few hours to finish my project, so i bought another ANE.

Sorry.

**Comment by myflashlab** [comment]
> Cannot access a property or method of a null object reference

you will see this error, usually when the ANE is not implemented correctly OR you might be testing on a simulator while you should be testing on a real device.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
