### ISSUE TITLE
Set size for resized picture - preserving exif info

### ISSUE THREAD

**Issue by msmpro** [myflashlab/fileChooser-ANE#4]
Hi,

I'm using the third parameter to create a resized picture, keeping the aspet ratio, but I don't know who can I set with o height to get the file with exactly the size I want.
I have a original file with this resolution 5312x2988 and I set the third parameter like this: {width:500, height:500, quality:50} and the result it's a picture with this resolution 664x374.
No one of the attributes, width or height is set to selected value, 500.
I never get the resized picture with setted values.

Then, how that works?
And one last thing, the resized image loose the exif info from oirignal file... than it's necessary to load the original one to get the good orientation of image. it's possible to fix this?

Thanks in advance.

**Comment by myflashlab** [comment]
Thanks for spotting that bug! we just updated the ANE to V4.0.1 try the new ANE and the problem is solved.

about preserving exif info of images, unfortunately that information is lost. I will mark this request as a feature so we can later add it to the ANE.

**Comment by msmpro** [comment]
Thanks for fixing the problem with resized picture resolution! Now works correctly.
I think, the exif info of images it's absolutly necessary to use the resize feature of your ANE.

Thank you.

**Comment by kakarlus** [comment]
Hi @myflashlab ,

I also tried setting the parameters as below
fileChooser.choose("image/*", "Pick an image.", {width: 500, height: 500, quality: 80});

And saved the image to Firebase Storage(REST), the image didn't get resized.

Regards,
Carlos

**Comment by myflashlab** [comment]
@kakarlus Are you sure you are using the resized image? check [this sample](https://github.com/myflashlab/fileChooser-ANE/blob/master/FD/src/MainFinal.as#L259-L281).

```actionscript
		private function onResult(e:FileChooserEvent):void
		{
			var originalFile:File = e.param.original;
			
			C.log("original file.name = " + originalFile.name);
			C.log("original file.extension = " + originalFile.extension);
			C.log("original file.size = " + FileSizeConvertor.size(originalFile.size));
			C.log("");
			
			// e.param.resized is only available if you are picking an image and have specified the resize object for it.
			var resizedFile:File = e.param.resized;
			if (resizedFile) 
			{
				C.log("resized file.name = " + resizedFile.name);
				C.log("resized file.extension = " + resizedFile.extension);
				C.log("resized file.size = " + FileSizeConvertor.size(resizedFile.size));
				C.log("resized path = " + resizedFile.url);
				
			}
			
			C.log("------------------------------");
			
}
```

**Comment by kakarlus** [comment]
@myflashlab i was still using the original, e.param.resized solved it cheers!

**Comment by kakarlus** [comment]
hi @myflashlab the resized image is still losing the exif data :(

**Comment by myflashlab** [comment]
We have not yet implemented this enhancement. It's in our to-do list. will update this ticket as soon as it's implemented.

**Comment by kakarlus** [comment]
hi @myflashlab thanks :) do you have any timeline in mind? 

so i'd know if i want to wait or create a workaround

**Comment by myflashlab** [comment]
Well, we have the new code added into the Android side, but not yet into the iOS side... Anyhow, will you be able to test [this demo ane](https://drive.google.com/file/d/0B7eHG2CEml2Tc3hra0RkYkR3SUE/view?usp=sharing) (on Android) and tell us if the exif info is correctly returned?

**Comment by msmpro** [comment]
Thank you @myflashlab for your time! I don't have time right now to test your demo for Android, maybe in a few days.
I hope @kakarlus hastime to check it soon.

**Comment by kakarlus** [comment]
will try to find time over the weekend :D

**Comment by kakarlus** [comment]
i've tried the demo ane. loaded it thru ExifLoader (https://github.com/bashi/exif-as3) but it doesn't work. not sure if it's my code or the demo ANE

**Comment by kakarlus** [comment]
any news @myflashlab ?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
