### ISSUE TITLE
fileChooser browser orientation on iOS

### ISSUE THREAD

**Issue by hans-ahrens** [myflashlab/fileChooser-ANE#6]
When the app is oriented in landscape mode then the fileChooser browser should also be rotated in landscape mode. Now its always oriented in portrait mode oriented to the Home button of the Ipad.
The problem occurs on an iPad 3 and iPad Air with iOS 9.3.1.

**Comment by daejoonpark** [comment]
Android also this problem my test samsung galaxys4

**Comment by jimmymjing** [comment]
Please add this feature

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
