### ISSUE TITLE
Build Error - Cant find script

### ISSUE THREAD

**Issue by PixelsGD** [myflashlab/fileChooser-ANE#7]
Hello. I wrote and email earlier but I believe you may prefer this method...

I unzipped the file from my download link and created a project top level within that folder.
Copied the code from your readme to call the script.
Edited the XML to include the copied line from your readme.
Back in to Adobe Animate and Test build. It will compile to the end and then return the following error:

> Scene 1, Layer 'Layer 1', Frame 1, Line 10, Column 21 1046: Type was not found or was not a compile-time constant: FileChooserEvent.

I followed the "com.myflashlab.air.extensions.fileChooser.FileChooser" folder location down and when I opened it all I found was html files. I've tried coping the ANE and SWC files in every folder hoping that was it. I've renamed the location. No matter what I do it seems Animate can not find the actual script to link. I have spend 7 hours on this problem..this one line error and no closer to a solution. My Android APK appears to be the latest, though I'll try to manually update in the mean time while I await your advice. Thank you!

**Comment by myflashlab** [comment]
@PixelsGD The error message shows that you have not yet embedded the ANE into your project. Please watch this videos and  they will show common mistakes devs would make while using ANEs.
> I followed the "com.myflashlab.air.extensions.fileChooser.FileChooser" folder location down and when I opened it all I found was html files.

You should not put the ANE files there! no matter what IDE you are using, whether it's FlashCC/FB or FD, there is a standard way on how you should implement ANEs into your project. If the above video clips didn't help you (which is unlikely) you should do some Googling about how to implement and use an ANE into your project, there are tones of tutorials about this.

**Note:** the swc file is no longer needed and you can make your project work with the .ane file alone but we have put the swc in the download package just for the sake of old times.

**Note2:** you should not try to run the ANE on a simulator, please use a physical device.

Let me know if this information is helpful?

**Comment by PixelsGD** [comment]
Hi myflashlab. I searched youtube for your video and found a couple. "Episode 2: How to implement an ANE into your project using FlashBuilder". Unfortunately this did not help as I am using Adobe Animate.  Builder doesn't seem to import my Animate project. I have searched over and over for a tutorial to embed a ANE with Animate but everyone only seems to use Flash Builder. I can not find a BAT to edit nor any file structure. All I have is the FLA, SWF, ANE and XML. I have manually searched every option in Animate and added the library to the ActionScript Settings menu, which return a new error. These errors won't allow any kind of build either so I can not even get it generate:

> Scene 1, Layer 'Layer 1', Frame 1, Line 12, Column 14	1046: Type was not found or was not a compile-time constant: File.
> Scene 1, Layer 'Layer 1', Frame 1, Line 12, Column 41	1120: Access of undefined property File.
> Scene 1, Layer 'Layer 1', Frame 1, Line 15, Column 28	1120: Access of undefined property FileSizeConvertor.

Still stuck on this. I'm sorry if I'm giving you trouble.

Thanks, Kevin

**Comment by myflashlab** [comment]
I just updated Hadi about this and he's installing a FlashCC and will soon record a new screencast explaining how to embed ANEs into FlashCC.Please watch out the playlist here https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by PixelsGD** [comment]
Still getting errors even though Ive imported the ANE succesfully. Same errors actually. I've attached screen shots of the code as well as of the how-to-import ANE. My XML does have the code listed in the Manifest and if I "break" the code in the XML I get a separate build error. So I don't think it's there but I could be wrong.
![errors](https://cloud.githubusercontent.com/assets/19581584/15726879/1568e890-2808-11e6-978d-eb9994d14992.jpg)

Below are screenshots on where to install the ANE in Adobe Animate (latest edition). It's actually easy to find once you know what you're looking for. 

![1](https://cloud.githubusercontent.com/assets/19581584/15726704/3fc567c2-2807-11e6-9d88-7f62391b22c6.jpg)

![2](https://cloud.githubusercontent.com/assets/19581584/15726713/4aec1e3e-2807-11e6-8a15-95e3cd828760.jpg)

![3](https://cloud.githubusercontent.com/assets/19581584/15726721/50e0b70a-2807-11e6-9d71-a5f59a86afa6.jpg)

![4](https://cloud.githubusercontent.com/assets/19581584/15726728/58eb8ad8-2807-11e6-8392-eb2d519dfe8d.jpg)

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
