### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by theadisim** [myflashlab/fileChooser-ANE#8]
`Error: The extension com.myflashlab.air.extensions.fileBrowser has either a namespace version or library.swf with a version that is incompatible with the applications namespace or root SWF.`

I've updated my AIR SDK up to the newest, while trying to compile this error comes up...
I got no idea what to do

**Comment by myflashlab** [comment]
Well, upgrading the AIR SDK alone is not enough. Please confirm if your namespace is now also updated? The current latest AIR version is 23, your name space should look like this:

```xml
<application xmlns="http://ns.adobe.com/air/application/23.0">
```

Besides that, it's a good idea to set the ```-swf-version``` of your app also to value 33 or 34

```
-swf-version=34
```

**Comment by myflashlab** [comment]
Will you update the issue and close it if you don't have a question on this regard?
