### ISSUE TITLE
(iOS) Can't create Bitmap from File

### ISSUE THREAD

**Issue by mrgoonie** [myflashlab/fileChooser-ANE#9]
I picked a photo but when I tried to read File's data as a Bitmap, it was failed:

Errors:
```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at ImagePickerANE_fla::MainTimeline/onResult()[ImagePickerANE_fla.MainTimeline::frame1:30]
	at ImagePickerANE_fla::MainTimeline/onResult()
	at com.myflashlab.air.extensions.fileChooser.ios::Ios/onStatus()
	at com.myflashlab.air.extensions.fileChooser.ios::Ios/onStatus()
```

My code:
```
...
function onResult(e:FileChooserEvent):void
{
    var file:File = e.param.original as File;
    trace("file.name = " + file.name);
    trace("file.extension = " + file.extension);
    trace("file.size = " + file.size );
	trace("file.data.length = " + file.data.length);
    trace("------------------------------");
	
	var loader:Loader = new Loader();             
    loader.contentLoaderInfo.addEventListener(Event.COMPLETE, function(e:Event):void{
        var bm:Bitmap = Bitmap(e.target.content as Bitmap);
        bm.smoothing = true;
		
		bm.width = stage.stageWidth;
		bm.scaleY = bm.scaleX;
		
        scope.load(bm)
    }); 
    loader.loadBytes(file.data);
}
...
```

I checked, the "file.data" is _null_

**Comment by myflashlab** [comment]
what are the output of the following traces?
```actionscript
trace("file.name = " + file.name);
trace("file.extension = " + file.extension);
```
can you confirm if the file really exists? ```file.exist()```

**Comment by mrgoonie** [comment]
It's existed. It returned the name of the photo (which is some number) and the file.extension = "jpg"

However, I've done a workaround by loading the "file.url" and it worked so far.

But the "file.data" should work too, shouldn't it?

**Comment by myflashlab** [comment]
After reconsidering the question, I think it IS correct for the file.data to be null because the returned file instance is just a reference to the selected file. We are not loading the file upon being elected or the AIR app could easily run out of memory. The ANE is leaving the decision to load the file to you. So, yes, using the file url to load the image is not a workaround but the actual approach :)

**Comment by mrgoonie** [comment]
Alright, lets close this!
